services:
  - type: web
    name: php-rest-api
    runtime: docker
    repo: https://github.com/chamiESWYB/musfac-api
    branch: main
    envVars:
      - key: HOST
        value: musfacdb-musfac.l.aivencloud.com
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        value: AVNS_SaWz0jUU6rz9dOah3-l
