services:
  - type: web
    name: musfac-api
    runtime: docker
    repo: https://github.com/chamiESWYB/musfac-api
    branch: main
    envVars:
      - key: HOST
        value: sql307.infinityfree.com
      - key: DB_NAME
        value: if0_38357642_mufac_rest_api
      - key: DB_USER
        value: if0_38357642
      - key: DB_PASS
        value: 22694Wcc123
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t ."